-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES 
FROM BOOK AS B, AUTHOR AS A, BOOK_SALES AS B_S
WHERE B.AUTHOR_ID = A.AUTHOR_ID AND B.BOOK_ID = B_S.BOOK_ID 
    AND YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;